version = 0.1

[default.deploy.parameters]
stack_name = "voice-memo"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
confirm_changeset = true
s3_prefix = "voice-memo"
parameter_overrides = "BucketName=\"aws-voice-memo\""
image_repositories = []

[default.global.parameters]
region = "ap-southeast-2"
